/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://l56uufcd7zcrjl7qfzld3562hm.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6hwdkp4ibjcbpckfusxwtbiaf4",
    "aws_cognito_identity_pool_id": "eu-central-1:0d82c60c-3e4d-4cd1-b33c-3cc32ea6ea72",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_96jvUcjbi",
    "aws_user_pools_web_client_id": "6mvd7asakt2hq5qvjqrl9bq6qj",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
